import Fragment.Algebra.Algebra
import Fragment.Algebra.Combinators
import Fragment.Algebra.Coproduct
import Fragment.Algebra.Homomorphism
import Fragment.Algebra.Homomorphism.Base
import Fragment.Algebra.Homomorphism.Definitions
import Fragment.Algebra.Homomorphism.Equivalence
import Fragment.Algebra.Homomorphism.Properties
import Fragment.Algebra.Homomorphism.Setoid
import Fragment.Algebra.Initial
-- import Fragment.Algebra.Quotient
import Fragment.Algebra.Signature
import Fragment.Algebra.Free
import Fragment.Algebra.Free.Base
import Fragment.Algebra.Free.Properties
import Fragment.Algebra.Free.Monad
import Fragment.Algebra.Free.Evaluation
import Fragment.Algebra.Free.Substitution
import Fragment.Setoid.Morphism
import Fragment.Setoid.Morphism.Base
import Fragment.Setoid.Morphism.Setoid
import Fragment.Setoid.Morphism.Properties
{-
import Fragment.Equational.Coproduct
import Fragment.Equational.FreeExtension
import Fragment.Equational.FreeModel
import Fragment.Equational.FreeModel.Base
import Fragment.Equational.FreeModel.Properties
import Fragment.Equational.Initial
import Fragment.Equational.Model
import Fragment.Equational.Satisfaction
import Fragment.Equational.Structures
import Fragment.Equational.TermModel
import Fragment.Equational.TermModel.Base
import Fragment.Equational.TermModel.Properties
import Fragment.Equational.TermModel.ProvableEquivalence
import Fragment.Equational.Theory
import Fragment.Equational.Theory.Base
import Fragment.Equational.Theory.Bundles
import Fragment.Equational.Theory.Combinators
import Fragment.Equational.Theory.Laws
import Fragment.Examples
import Fragment.Extensions.Base
import Fragment.Extensions.Combinators
import Fragment.Extensions.Semigroup
import Fragment.Macros.Base
import Fragment.Macros.Environment
import Fragment.Macros.Fin
import Fragment.Macros.Fragment
import Fragment.Prelude
-}
