import Fragment.Algebra.Algebra
import Fragment.Algebra.Coproduct
import Fragment.Algebra.FreeAlgebra
import Fragment.Algebra.FreeAlgebra.Base
import Fragment.Algebra.FreeAlgebra.Definitions
import Fragment.Algebra.FreeAlgebra.Properties
import Fragment.Algebra.Homomorphism
import Fragment.Algebra.Homomorphism.Base
import Fragment.Algebra.Homomorphism.Definitions
import Fragment.Algebra.Homomorphism.Equivalence
import Fragment.Algebra.Homomorphism.Properties
import Fragment.Algebra.Homomorphism.Setoid
import Fragment.Algebra.Initial
import Fragment.Algebra.Signature
import Fragment.Algebra.TermAlgebra
import Fragment.Algebra.TermAlgebra.Base
import Fragment.Algebra.TermAlgebra.Properties
import Fragment.Algebra.TermAlgebra.Syntax
import Fragment.Equational.Bundles
import Fragment.Equational.Laws
import Fragment.Equational.Model
import Fragment.Equational.Structures
import Fragment.Equational.Theory
